ekf_filter_node:
  frequency: 30
  sensor_timeout: 0.1

  # IMU configuration
  imu0: /imu_topic
  imu0_config: [false, false, false, true, true, true, false, false, false, true, true, true]
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  # LiDAR configuration
  lidar0: /lidar_topic
  lidar0_config: [true, true, true, false, false, false, false, false, false, false, false, false]
  lidar0_queue_size: 10
